### PR TITLE
Rails 5.2 compatibility - Monkeypatch ActiveModel::Dirty

### PR DESCRIPTION
**Pull request by garettarrowood**
I am able to reproduce breaking change as summarized in #13 by raising my `active_model` and `active_support` versions to 5.2. The test suite fails 77 times with:

```
      NoMethodError:
        undefined method `changed?' for nil:NilClass
      # /Users/garettarrowood/.rvm/gems/ruby-2.4.1/gems/activemodel-5.2.2/lib/active_model/attribute_mutation_tracker.rb:49:in `changed?'
      # /Users/garettarrowood/.rvm/gems/ruby-2.4.1/gems/activemodel-5.2.2/lib/active_model/dirty.rb:292:in `changes_include?'
      # /Users/garettarrowood/.rvm/gems/ruby-2.4.1/gems/activemodel-5.2.2/lib/active_model/dirty.rb:176:in `attribute_changed?'
      # /Users/garettarrowood/.rvm/gems/ruby-2.4.1/gems/activemodel-5.2.2/lib/active_model/dirty.rb:314:in `attribute_will_change!'
      # /Users/garettarrowood/.rvm/gems/ruby-2.4.1/gems/activemodel-5.2.2/lib/active_model/attribute_methods.rb:382:in `name_will_change!'
      # ./lib/modis/attribute.rb:70:in `name='
      # ./spec/validations_spec.rb:27:in `block (3 levels) in <top (required)>'
```

Adding this file makes the test suite run green.

It would be ideal if I could establish a matrix in the `.travis.yml` to test various versions. This may be accomplishable by setting it up with a `RAILS_ENV`. But that feels hacky, considering there is no rails here.

More ideal is not applying a monkey patch.

I am open to suggestions.

### CODE REVIEW

**Comment by benlangfeld** [comment]
It's definitely a good idea to setup a matrix to ensure your changes are backward compatible. It's also preferable to re-write the failing code using the newer APIs.

**Comment by garettarrowood** [comment]
* My older version of rubocop (0.52.1) did not catch these new offenses. When I upgrade to the version in CI (0.61.1), I am able to reproduce the violations. I will open another PR to resolve these, and lock in a rubocop version. There's no need to keep battling the updates.

@benlangfeld - I'll experiment establishing a matrix with `RAILS_ENV` env vars.

**Comment by garettarrowood** [comment]
Looks like matrix work was started in #9 .

**Comment by benlangfeld** [comment]
I propose closing this in favour of https://github.com/ileitch/modis/pull/19 .
